In [25]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import  make_pipeline
from sklearn.preprocessing import StandardScaler

In [4]:
np.random.seed(42)
fastball_speed = np.random.randint(90,106, size=500)
tomy_john = np.where(fastball_speed>96, np.random.choice([0,1], size=500, p=[0.3,0.7]),0)
d = {"fastball_speed": fastball_speed, "tomy_john":tomy_john}
df = pd.DataFrame(d)
df.head()

fastball_speed  tomy_john
0              96          0
1              93          0
2             102          1
3             104          1
4             100          0

In [7]:
X = df[['fastball_speed']]
y = df[['tomy_john']]

In [10]:
# normal train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [11]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_train,y_train)

c:\Python312\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.7425

In [14]:
#  basic cross validation
cv = cross_val_score(lr, X,y.values.ravel(), cv=10)
cv

array([0.68, 0.78, 0.72, 0.72, 0.78, 0.82, 0.74, 0.74, 0.76, 0.82])

In [15]:
np.average(cv)

0.756

In [23]:
# cross val with KFold Stratified
kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
cv2 = cross_val_score(lr, X,y.values.ravel(), cv=kfold, scoring="accuracy")
cv2

array([0.8 , 0.84, 0.64, 0.8 , 0.74, 0.72, 0.78, 0.8 , 0.7 , 0.74])

In [24]:
np.average(cv2)

0.756

In [30]:
np.std(cv2)

0.05642694391866354

In [26]:
# example with pipleline
scalar = StandardScaler()
pipe = make_pipeline(scalar, lr)

In [27]:
cv3 = cross_val_score(pipe,X,y.values.ravel(), cv=15)
cv3

array([0.79411765, 0.67647059, 0.70588235, 0.67647059, 0.76470588,
       0.75757576, 0.72727273, 0.84848485, 0.78787879, 0.72727273,
       0.6969697 , 0.81818182, 0.72727273, 0.78787879, 0.84848485])

In [28]:
np.average(cv3)

0.7563279857397504

In [29]:
np.std(cv3)

0.055170996263225365

In [ ]:
#  grid search and using 